Fix output/encoding handling for python-3 (belongs to 8ef8473)
gocept/gocept.jslint pull request #10
Opened 2021-04-21 12:00 UTC by wosc

The previous spelling breaks in line 112 "if pattern in line" since pattern usually is text. Also it probably makes the most sense to decode once an be done with it.

2021-04-22 14:33 UTC, icemac commented
@wosc That's interesting, we are using this package on Python 3.7 without any problems. Do you see a reason why no test breaks?

2021-04-29 12:11 UTC, wosc commented
@icemac as it turns out, the tests were blatantly lying ;)

2021-04-30 06:13 UTC, icemac requested changes
Thank you for fixing the code and the tests, LGTM.
Could you please additionally add a change log entry.
Afterwards I could merge and cut a new release.

2021-05-07 06:53 UTC, icemac approved these changes

2021-05-07 06:53 UTC, merged

2021-05-07 06:53 UTC, icemac commented
Thank you for this PR. 😀

2021-05-07 06:56 UTC, icemac commented
Just released as https://pypi.org/project/gocept.jslint/3.0/.

2021-05-10 06:28 UTC, wosc commented
Thanks for the release!